In [1]:
import sys
import argparse
import configparser
import copy
import numpy as np

import reader
#import neuralnet_p1 as p1
#import neuralnet_p2 as p2
#import neuralnet_p3 as p3
import torch

In [2]:
x=torch.rand(1,3)

In [3]:
x

tensor([[0.3420, 0.9968, 0.6595]])

In [4]:
X_train = np.load( 'X_train_part1.npy')
y_train = np.load('y_train_part1.npy')
X_dev   = np.load('X_dev_part1.npy')
y_dev   = np.load( 'y_dev_part1.npy')

In [12]:
train_set=torch.tensor(X_train,dtype=torch.float32)
train_set[7499].shape

torch.Size([784])

In [35]:
XX=train_set.view(len(X_train),1,28,28)

In [45]:
XX[0][0]

tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,  40.,  46.,
           0.,   1.,   0.,   0.,   0.,   3.,  64.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  57.,  42.,
           0.,   1.,   1.,   0.,   0.,   1.,  61.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   2.,   0., 127., 100.,
           0.,   0.,   0.,   0.,   0.,  52., 199.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 212., 219.,
           0.,   0.,   0.,   0.,  30., 190., 153.,  55.,   0.,   1.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 116., 224., 243.,
         225.,   0.,   0.,  24., 241., 161., 122.,  93.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,

In [8]:
k=0
for i in range(7500):
    k+=torch.mean(XX[i])
k/7500

tensor(74.1465)

In [9]:
torch.mean(XX)

tensor(74.1466)

In [29]:
XX[0].shape

torch.Size([28, 28])

In [30]:
Variable(XX)

NameError: name 'Variable' is not defined

In [26]:
input = torch.randn(1,64,64,3)
input.shape

torch.Size([1, 64, 64, 3])

In [27]:
input=input.view(1,64*64*3)
input.shape

torch.Size([1, 12288])

In [28]:
input

tensor([[ 2.2735, -0.6441, -0.5441,  ...,  1.4340, -0.1263, -1.2018]])

In [46]:
A=[]

In [47]:
A.append(0.1)

In [48]:
A[-1]

0.1

In [ ]:
A.append