In [1]:
import numpy as np

In [3]:
epsilon=0.6
decision = np.random.uniform(0, 1)
if decision < epsilon:
    pi = np.ones(3) / 3
else:
    pi = np.zeros(3)
    pi[0] = 1.0
pi

array([0.33333333, 0.33333333, 0.33333333])

In [4]:
np.random.choice([0,1,2],1,p=pi)

array([1])

In [5]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
import pandas as pd

In [6]:
A=pd.DataFrame(np.zeros((3, 4)))

In [7]:
A[0][0]

0.0

In [10]:
A=np.zeros((3,3) + (4,))[0][1]

In [11]:
state=np.array([2,3])

In [13]:
A[state[np.newaxis]][0]

array([0., 0.])

In [2]:
import gym 
env = gym.make('MountainCar-v0')


In [7]:
env.observation_space.shape[0]

2

In [10]:
class test():
    def __init__(self, env,buckets):
        self.env=env
        self.buckets=(3,2)
        
    def discretize(self,obs):
        upper_bounds = [self.env.observation_space.high[0], self.env.observation_space.high[1]]
        lower_bounds = [self.env.observation_space.low[0], self.env.observation_space.low[1]]
        ratios = [(obs[i] + abs(lower_bounds[i])) / (upper_bounds[i] - lower_bounds[i]) for i in range(len(obs))]
        new_obs = [int(round((self.buckets[i] - 1) * ratios[i])) for i in range(len(obs))]
        new_obs = [min(self.buckets[i] - 1, max(0, new_obs[i])) for i in range(len(obs))]

In [11]:
env = gym.make('MountainCar-v0')
env.reset()
goal_steps = 200
score_requirement = -198
intial_games = 10000
obs=[]
def play_a_random_game_first():
    for step_index in range(goal_steps):
        env.render()
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        obs.append(observation)
        print("Step {}:".format(step_index))
        print("action: {}".format(action))
        print("observation: {}".format(observation))
        print("reward: {}".format(reward))
        print("done: {}".format(done))
        print("info: {}".format(info))
        if done:
            break
    env.reset()

In [12]:
play_a_random_game_first()

Step 0:
action: 0
observation: [-0.4613687  -0.00147488]
reward: -1.0
done: False
info: {}
Step 1:
action: 2
observation: [-0.46230761 -0.0009389 ]
reward: -1.0
done: False
info: {}
Step 2:
action: 0
observation: [-0.46470361 -0.002396  ]
reward: -1.0
done: False
info: {}
Step 3:
action: 0
observation: [-0.46853903 -0.00383542]
reward: -1.0
done: False
info: {}
Step 4:
action: 2
observation: [-0.47178552 -0.00324649]
reward: -1.0
done: False
info: {}
Step 5:
action: 0
observation: [-0.47641905 -0.00463353]
reward: -1.0
done: False
info: {}
Step 6:
action: 1
observation: [-0.48140525 -0.0049862 ]
reward: -1.0
done: False
info: {}
Step 7:
action: 1
observation: [-0.48670705 -0.0053018 ]
reward: -1.0
done: False
info: {}
Step 8:
action: 0
observation: [-0.49328498 -0.00657793]
reward: -1.0
done: False
info: {}
Step 9:
action: 2
observation: [-0.49908995 -0.00580497]
reward: -1.0
done: False
info: {}
Step 10:
action: 1
observation: [-0.50507856 -0.00598862]
reward: -1.0
done: False
info: {

Step 91:
action: 2
observation: [-0.6247058  -0.00597525]
reward: -1.0
done: False
info: {}
Step 92:
action: 1
observation: [-0.62993432 -0.00522852]
reward: -1.0
done: False
info: {}
Step 93:
action: 2
observation: [-0.63337878 -0.00344446]
reward: -1.0
done: False
info: {}
Step 94:
action: 2
observation: [-0.63501469 -0.00163591]
reward: -1.0
done: False
info: {}
Step 95:
action: 2
observation: [-6.34830453e-01  1.84234307e-04]
reward: -1.0
done: False
info: {}
Step 96:
action: 2
observation: [-0.63282738  0.00200308]
reward: -1.0
done: False
info: {}
Step 97:
action: 2
observation: [-0.62901967  0.00380771]
reward: -1.0
done: False
info: {}
Step 98:
action: 2
observation: [-0.62343442  0.00558525]
reward: -1.0
done: False
info: {}
Step 99:
action: 0
observation: [-0.61811155  0.00532287]
reward: -1.0
done: False
info: {}
Step 100:
action: 2
observation: [-0.61108929  0.00702226]
reward: -1.0
done: False
info: {}
Step 101:
action: 2
observation: [-0.60241836  0.00867093]
reward: -1.0

observation: [-0.43403529  0.0071694 ]
reward: -1.0
done: False
info: {}
Step 185:
action: 1
observation: [-0.42752956  0.00650573]
reward: -1.0
done: False
info: {}
Step 186:
action: 0
observation: [-0.42273441  0.00479515]
reward: -1.0
done: False
info: {}
Step 187:
action: 2
observation: [-0.41768426  0.00505015]
reward: -1.0
done: False
info: {}
Step 188:
action: 0
observation: [-0.41441516  0.00326909]
reward: -1.0
done: False
info: {}
Step 189:
action: 2
observation: [-0.41095038  0.00346478]
reward: -1.0
done: False
info: {}
Step 190:
action: 1
observation: [-0.40831447  0.00263591]
reward: -1.0
done: False
info: {}
Step 191:
action: 0
observation: [-0.40752606  0.00078841]
reward: -1.0
done: False
info: {}
Step 192:
action: 1
observation: [-4.07590709e-01 -6.46476937e-05]
reward: -1.0
done: False
info: {}
Step 193:
action: 0
observation: [-0.40950796 -0.00191725]
reward: -1.0
done: False
info: {}
Step 194:
action: 1
observation: [-0.41226428 -0.00275632]
reward: -1.0
done: Fals

In [13]:
#env.step(action)

In [12]:
obslist=obs

In [13]:
env.action_space.n

3

In [14]:
pi

array([1., 0., 0.])

In [15]:
action = np.random.choice(env.action_space.n,1,p=pi)[0]

In [16]:
action

0

In [17]:
env.reset()
obs, reward, done, info = env.step(action)
obs, reward, done, info 

(array([-6.00346416e-01, -4.32624439e-04]), -1.0, False, {})

In [18]:
len(obs)

2

In [19]:
env.action_space.sample()

0

In [20]:
obs

array([-6.00346416e-01, -4.32624439e-04])

In [39]:
buckets=(100,100)
upper_bounds = [env.observation_space.high[0], env.observation_space.high[1]]
print('upperbounds is ',upper_bounds)
lower_bounds = [env.observation_space.low[0], env.observation_space.low[1]]
print('lowerbounds is', lower_bounds)
ratios = [(obs[i] + abs(lower_bounds[i])) / (upper_bounds[i] - lower_bounds[i]) for i in range(len(obs))]
print(ratios)
new_obs = [int(round((buckets[i] - 1) * ratios[i])) for i in range(len(obs))]
new_obs = [min(buckets[i] - 1, max(0, new_obs[i])) for i in range(len(obs))]


upperbounds is  [0.6, 0.07]
lowerbounds is [-1.2, -0.07]
[0.3331408934431165, 0.4969098254496985]


In [40]:
new_obs

[33, 49]

In [23]:
env.observation_space.high[0]

0.6

In [24]:
env.observation_space

Box(2,)

In [25]:
C=np.zeros((3,3) + (4,))

In [26]:
C.shape

(3, 3, 4)

In [27]:
C[0][2]

array([0., 0., 0., 0.])

In [28]:
(1,3)[0]

1

In [29]:
np.array(np.array([0,1]))

array([0, 1])

In [30]:
len(np.array([[1,2,3]]))

1

In [35]:
new_obs
new_obs=np.array(new_obs)

In [38]:
len(new_obs[np.newaxis][0])

2

In [43]:
np.argmax(np.array([10, 11, 12, 13, 10, 15]))

5

In [2]:
import gym

In [3]:
env=gym.make('CartPole-v0')

In [9]:
env.action_space

Discrete(2)

In [12]:
env.observation_space.shape[0]

4

In [22]:
env.reset()
type(env.step(0)[0][0])

numpy.float64